server:
  port: 8080
  log_level: debug

database:
  host: localhost
  port: 5432
  user: postgres
  password: changeme
  dbname: mcgonalds_db
  sslmode: disable

jwt:
  secret: your_jwt_secret_key
  expiration: 24h

minio:
  endpoint: localhost:9000
  accesskey: xooUvEKzx7Nm78sXIfd5
  secretkey: 9IcBk9vJTn2hwi6Vbn574JkYsRk1iUqpwj23i5G6
  use_ssl: false
# should change to load from env